name: PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum

    - name: Download latest UI release
      run: |
        gh release download --repo Labbs/nexo-ui --pattern 'nexo-ui-dist.tar.gz' --output nexo-ui-dist.tar.gz
        mkdir -p infrastructure/static/files
        tar -xzf nexo-ui-dist.tar.gz -C infrastructure/static/files
        rm nexo-ui-dist.tar.gz
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build app
      run: CGO_ENABLED=1 GOOS=linux go build -a -ldflags '-linkmode external -extldflags "-static"' -o bin/app cmd/cmd.go
